apiVersion: v1
kind: ConfigMap

metadata:
  name: starter-app-config
  namespace: capstone

data:
  APP_NAME: "starter-app"
  APP_VERSION: "1.0.0"
  GREETING: "Hello, world!"
  PORT: "8080"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
